### PR TITLE
SES-798: Test suite fix.

### PR DESCRIPTION
**Pull request by joeyJsonar**
During unit test run, chrome.getApp() throws an exception. This is confirmed to be the case in vanilla kibana.

### CODE REVIEW

**Comment by michaelJSonar** [comment]
Not sure we should be merging this to `master`?

**Comment by RachelJsonar** [comment]
I think master is the default for this submodule: https://github.com/jsonar/kibana/blob/development/.gitmodules

**Comment by michaelJSonar** [comment]
Oh, I meant that since this change is intended to go with the test suite in https://github.com/jsonar/kibana/pull/470, which is for `development-4.x`, maybe we should merge to a 4.x branch in this repository too? Or just hold off on merging until after 4.0 is released?

**Comment by RachelJsonar** [comment]
ooooh yeah good point.

**Pull request merged**
